import { ii, ih, eh, ey, uh, uu, ear, ah, oh, ar, or, oo, ohw, er, ow, air, aj, oy } from '@/glyphs/vowels'
import { sh, l, h, d, b, v, g, s, j, k, t, r, z, n, p, dj, tj, tdh, tfh, vh, m, f,ng,ch} from '@/glyphs/consonants'
import type { GlyphOrJoin } from '@/utils'

export const page00: Record<string, GlyphOrJoin[]> = {
  secret: [[s,ii],k,[r,ih],t],
  legend: [[l,eh],[dj,eh],n,d],
}

export const page01: Record<string, GlyphOrJoin[]> = {
  the: [[tdh,uh]],
  softest:[[s,oh],f,[t,ih],s,t],
  feather: [[f,eh],[tdh,er]],
  corrected:[[k,or],[eh,k],[t,ih],d],
  eleven: [[eh,l],[eh,vh],[ih,n]],
  times: [[t,aj],m,z],
  departed: [[d,ii],[p,ar],[t,ih],d],
  once: [[v,uh],n,s],
  more: [[m,or]],
}
export const page02: Record<string, GlyphOrJoin[]> = {
  cards: [[k,ar],d,z],
  praying:[p,[r,ey],[ih,ng]],
  the:[[tdh,uh]],
  far:[[f,ar]],
  shore:[[sh,or]]
}

export const page03: Record<string, GlyphOrJoin[]> = {
  there: [[tdh,air]],
  lived: [[l,ih],vh,d],
  a:[uh],
  of: [[uh,vh]],
  great: [g,[r,ey],t],
  power: [[p,ow],er],
  they: [[tdh,ey]],
  built: [[b,ih],l,t],
  city: [[s,ih],[t,ii]],
  and: [[ah,n],d],
  within:[[v,ih],[tfh,ih],n],
  that: [[tdh,ah],t],
  palace:[[p,ah],[l,ih],s],
  held:[[h,eh],l,d],
  sacred:[[s,ey],k,[r,eh],d],
  secrets:[[s,ii],k,[r,ih],t,s],
  understood:[[uh,n],[d,er],s,[t,uu],d],
  plainer: [p,[l,ey],[n,er]],
  nature: [[n,ey],[tj,er]],
  reality: [[r,ii],[ah,l],[ih,t],ii],
  ventured: [[vh,eh],n,[tj,er],d],
  too: [[t,oo]],
  the: [[tdh,uh]],
  far: [[f,ar]],
  shore: [[sh,or]],
  sought: [[s,oh],t],
  from: [f,[r,uh],m],
  spaces: [s,[p,ey],[s,ih],z],
  between: [[b,ii],t,[v,ii],n],
  as:[[ah,z]],
  is:[[ih,z]],
  usual:[[j,oo],[ch,oo],[uu,l]],
  an:[[ah,n]],
  alluring: [[uh,l],[oo,r],[ih,ng]],
  old:[[oo,l],d],
  was:[[v,uh],z],
  discovered:[[d,ih],s,[k,uh],[vh,er],d],
  fossils:[[f,oh],[s,uu],l,z],
  self: [[s,eh],l,f],
  uneeld:[[uh,n],[ii,l],d],
  visions:[[vh,ih],[ch,uh],n,z],
  future: [f,[j,oo],[tj,er]],
  entombed: [[eh,n],[t,oo],m,d],
  cast:[[k,ah],s,t],
  into: [[ih,n],[t,oo]],
  sarcofagi:[[s,ar],[k,oh],[f,uh],[g,aj]],
  buried:[[b,air],[ii,d]],
  liver: [[l,ii],[vh,er]],
  in: [[ih,n]],
  canonical:[[k,ah],[n,oh],[n,ih],[k,uu],l],
  plain: [p,[l,ey],n],
  potential: [[p,oo],[t,eh],n,[sh,uu],l],
  perhaps:[[p,er],[h,ah],p,s],
  it: [[ih,t]],
  fabled: [[f,ey],[b,uu],h,l,d],
  price: [p,[r,aj],z],
}

export const page06: Record<string, GlyphOrJoin[]> = {
  canonical:[[k,uh],[n,oh],[n,ih],[k,uh],l],
  plain: [p,[l,ey],n],
}
export const page08: Record<string, GlyphOrJoin[]> = {
  thee:[[tdh,ii]],
  heir: [air],
}
export const page09: Record<string, GlyphOrJoin[]> = {
  options:[[uh,p],[sh,uh],n,z],
  mean:[[m,ii],n],
  can:[[k,ah],n],
  keep:[[k,ii],p],
  playing:[p,[l,ey],[ih,ng]],
  if:[[ih,f]],
  the:[[tdh,uh]],
  challenge:[[tj,ah],[l,eh],n,dj],
  is: [[ih,z]],
  to: [[t,oo]],
  much:[[m,uh],tj],
  right:[[r,aj],t],
  now:[[n,ow]],
  you:[[j,oo]],
  are:[ar],
  allowed:[[uh,l],[ow,d]],
  continue: [[k,uh],n,[t,ih],n,[j,oo]],
  most: [[m,ohw],s,t],
  recent: [[r,ii],[s,ih],n,t],
  file: [[f,aj],l],
  begin: [[b,eh],[g,ih],n],
  a:[uh],
  fresh:[f,[r,eh],sh],
  quest: [k,[v,eh],s,t],
  adjust: [[uh,dj],[uh,s],t],
  settings:[[s,eh],[t,ih],ng,z],
  go: [[g,ohw]],
  screen:[s,k,[r,ii],n],
  money: [[m,uh],[n,ii]],
  harder:[[h,ar],[d,er]],
  unknown:[[uh,n],[n,ohw],n],
  select: [[s,uh],[l,eh],k,t],
  whose: [[h,oo],z],
  this:[[tdh,ih],s],
  load:[[l,ohw],d],
  and: [[ah,n],d],
  resume: [[r,ii],[z,oo],m],
  play:[p,[l,ey]],
  choose:[[tj,oo],z],
  remove:[[r,ii],[m,oo],vh],
  forever:[[f,or],[eh,vh],er],
  customize:[[k,uh],s,[t,uh],[m,aj],z],
  your:[[j,or]],
  experience:[[eh,k],s,[p,ear],ii,[ih,n],s],
}
export const page11: Record<string, GlyphOrJoin[]> = {
  ruin: [[r,oo],[ih,n]],
  seeker: [[s,ii],[k,er]],
  you: [[j,oo]],
  strange:[s,t,[r,ey],n,dj],
  gate: [[g,ey],t],
  to: [[t,oo]],
  keep:[[k,ii],p],
  your: [[j,or]],
  eye: [aj],
  on:[[oh,n]],
  when:[[v,eh],n],
  have:[[h,ah],vh],
  are:[ar],
  in:[[ih,n]],
  danger:[[d,ey],n,[dj,er]],
}

export const page12: Record<string, GlyphOrJoin[]> = {
  controls: [[k, uh], n, t, [r, ohw], l, z],
  shield: [[sh, ii], l, d],
  potion: [[p, ohw], [sh, uh], n],
  use: [[j, oo], z],
  item: [[aj, t],[eh, m]],
  roll: [[r, ohw], l],
  run: [[r, uh], n],
  talk: [[t, oh], k],
  focus: [[f, ohw], [k, uh], s],
  is: [[ih,z]],
  crucial: [k,[r,oo],[sh,uu],l],
  inventory: [[ih,n],[vh,eh],n,[t,or],ii],
  gear: [[g,ear]],
  move: [[m, oo], vh]
}

export const page15: Record<string, GlyphOrJoin[]> = {

  represent:[[r,eh],p,[r,ii],[z,eh],n,t],
  your: [[j,or]],
  poise: [[p,oy],z],
  and:[[ah,n],d],
  strength:[s,t,[r,eh],ng,tfh],
  to: [[t,oo]],
  perform: [[p,er],[f,or],m],
  certain:[[s,er],[t,ih],n],
  actionz:[[ah,k],[sh,uh],n,z],
  when: [[v,eh],n],
  you: [[j,oo]],
  evade:[[ii,vh],[ey,d]],
  or:[or],
  other: [[uh,tdh],er],
  moves: [[m,oo],vh,z],
  go: [[g,ohw]],
  down:[[d,ow],n],
  at: [[ah,t]],
  can: [[k,ah],n],
  still:[s,[t,ih],l],
  do: [[d,oo]],
  many:[[m,eh],[n,ii]],
  actions:[[ah,k],[sh,uh],n,s],
  but: [[b,uh],t],
  a:[uh],
  disadvantage:[[d,ih],[s,ah],d,[vh,ah],n,[t,ih],dj],


  the: [[tdh,uh]],
  start:[s,[t,ar],t],
  of:[[uh,vh]],
  evasion: [[ii,vh],[ey,ch],[uh,n]],
  have:[[h,ah],vh],
  briefly:[b,[r,ii],f,[l,ii]],
  so: [[s,ohw]],
  just: [[dj,uh],s,t],
  rigth: [[r,aj],t],
  moment:[[m,ohw],[m,ih],n,t],

  take:[[t,ey],k],
  enough:[[ii,n],[uh,f]],
  hits:[[h,ih],t,s],
  will:[[v,ih],l],
  if:[[ih,f]],
  is:[[ih,z]],
  really:[[r,ii],[l,ii]],
  big:[[b,ih],g],
  even:[[ii,vh],[ih,n]],
  be:[[b,ii]],
  hidden: [[h,ih],[d,ih],n],
  gauge: [[g,ey],dj],
  total: [[t,ohw],[t,uu],l],
}

export const page17: Record<string, GlyphOrJoin[]> = {

  this:[[tdh,ih],s],
  heros:[[h,ear],[ohw,z]],
  blade:[b,[l,ey],d],
  forgery:[[f,or],[dj,er],ii],

  just: [[dj,uh],s,t],
  stick:[s,[t,ih],k],

  left:[[l,eh],f,t],
  by:[[b,aj]],
  use:[[j,oo],z],
  to:[[t,oo]],
  deflect:[[d,ii],f,[l,eh],k,t],
  blows:[b,[l,ohw],z],

  unstable:[[uh,n],s,[t,ey],[b,uu],l],
  powder:[[p,ow],[d,er]],
  fairy:[[f,air],ii],
  west:[[v,eh],s,t],
  garden:[[g,ar],[d,ih],n],


  made:[[m,ey],d],
  from:[f,[r,uh],m],
  slorm:[s,[l,or],m],
  pudding:[[p,uu],[d,ih],ng],
  that:[[tdh,ah],t],
  goes:[[g,ohw],z],
  boom:[[b,oo],m],

  fire:[[f,aj],er],
  everywhere:[[eh,vh],er,ii,[v,air]],
  and:[[ah,n],d],
  ow:[ow],

  you: [[j,oo]],
  need: [[n,ii],d],
  key: [[k,ii]],
  open: [[ohw,p],[eh,n]],
  of: [[uh,vh]],
  the:[[tdh,uh]],
  rare:[[r,air]],
  old:[[ohw,l],d],
  doors:[[d,or],z],
  disappears:[[d,ih],[s,uh],[p,ear],z],



  eat:[[ii,t]],
  fruits:[f,[r,oo],t,s],
  restore:[[r,ii],s,[t,or]],
  or:[or],
  they:[[tdh,ey]],
  are:[ar],
  gone:[[g,oh],n],
  forever:[[f,or],[eh,vh],er],
  so:[[s,ohw]],
  snack:[s,[n,ah],k],
  sparingly:[s,[p,air],[ih,ng],[l,ii]],

  one:[[v,uh],n],
  is:[[ih,z]],
  spicy:[s,[p,aj],[s,ii]],
  minty:[[m,ih],n,[t,ii]],
  gives:[[g,ih],vh,z],
  a:[uh],
  boost:[[b,oo],s,t],

  betray:[[b,ii],t,[r,ey]],
  for:[[f,or]],
  coins:[[k,oy],n,z],
  each:[[ii,tj]],
  betrayal:[[b,ii],t,[r,ey],[uu,l]],
  sweeter:[s,[v,ii],[t,er]],
  than:[[tdh,ah],n],
  last:[[l,ah],s,t],

  doll:[[d,oh],l],
  beloved:[[b,ii],[l,uh],[vh,ih],d],
  hero:[[h,ear],ohw],
  foes:[[f,ohw],z],
  will:[[v,ih],l],
  be:[[b,ii]],
  tricked:[t,[r,ih],k,t],


  special:[s,[p,eh],[sh,uu],l],
  treasure:[t,[r,eh],[ch,er]],
  allows:[[uh,l],[ow,z]],
  wish:[[v,ih],sh],
  at:[[ah,t]],
  well:[[v,eh],l],
  give:[[g,ih],vh],
  tier:[[t,ii],er],

  cards:[[k,ar],d,z],
  ways:[[v,ey],z],
  inspired:[[ih,n],s,[p,aj],[er,d]],
  unusual:[[uh,n],[j,oo],[ch,oo],[ah,l]],
  greatness:[g,[r,ey],t,[n,ih],s],
}
export const page23: Record<string, GlyphOrJoin[]> = {
  do:[[d,oo]],
  you:[[j,oo]],
  the:[[tdh,uh]],
  way:[[vh,ey]],
  go:[[g,ohw]],

  check:[[tj,eh],k],
  behind:[[b,ii],[h,aj],n,d],
  it:[[ih,t]],

  monastery:[[m,oh],[n,uh],s,[t,air],ii],
  fortress:[[f,or],t,[r,eh],s],
  forest:[[f,or],[eh,s],t],
  swamp:[s,[v,oh],m,p],
  library:[[l,aj],b,[r,air],ii],
  garden:[[g,ar],[d,ih],n],

  secret: [[s,ii],k,[r,ih],t],

  to: [[t,oo]],
  pray:[p,[r,ey]],
  be: [[b,ii]],
  still:[s,[t,ih],l],
  for:[[f,or]],
  a:[uh],

  ruin:[[r,oo],[ih,n]],
  seeker:[[s,ii],[k,er]],
  press: [p,[r,eh],s],
  hold:[[h,ohw],l,d],

  know:[[n,ohw]],
  holy:[[h,ohw],[l,ii]],
  being:[[b,ii],[ih,ng]],
  will:[[v,ih],l],
  ever: [[eh,vh],er],
  hear: [[h,ear]],

  give: [[g,ih],vh],
  of:[[uh,vh]],
  their:[[tdh,air]],
  core:[[k,or]],
  and:[[ah,n],d],
  awaken:[uh,[v,ey],[k,ih],n],
}
export const page24: Record<string, GlyphOrJoin[]> = {
  of: [[uh,vh]],
  prayer: [p,[r,ey],er],

  moment: [[m,ohw],[m,ih],n,t],
  and: [[ah,n],d],
  rest: [[r,eh],s,t],

  hold: [d],
  for: [[f,or]],
  a: [uh],
  short:[[sh,or],t],
  time: [[t,aj],m],

  you:[[j,oo]],
  but: [[b,uh],t],
  venerate:[[vh,eh],[n,er],[ey,t]],
  chose:[[sh,ohw],z],
  who: [[h,oo]],

  the:[[tdh,uh]],
  tools:[[t,oo],l,z],
  lost:[[l,oh],s,t],
  age:[[ey,dj]],

  praying: [p,[r,ey],[ih,ng]],
}

export const page30: Record<string, GlyphOrJoin[]> = {
  beneath: [[b,ii],[n,ii],tfh],
  earth:[[er,tfh]],
  are:[ar],
  many:[[m,eh],[n,ii]],
  scary:[s,[k,air],ii],
  places:[p,[l,ey],[s,ih],z],
  be:[[b,ii]],
  sure:[[sh,er]],
  to:[[t,oo]],
  take:[[t,ey],k],
  below:[[b,eh],[l,ohw]],
  fortress:[[f,or],t,[r,eh],s],
  is:[[ih,z]],
  a:[uh],
  cave:[[k,ey],vh],
}
export const page31: Record<string, GlyphOrJoin[]> = {
  one:[[vh,uh],n],
  key: [[k,ii]],
  to: [[t,oo]],
  is: [[ih,z]],
  guarded: [[g,ar],[d,ih],d],
  by:[[b,aj]],
  last:[[l,ah],s,t],
  great:[g,[r,ey],t],
  machine:[[m,uh],[sh,ii],n],
  of: [[uh,vh]],
  war: [[v,or]],
  when: [[v,eh],n],
  siege: [[s,ii],dj],
  was:[[v,uh],z],
  done:[[d,uh],n],
  this:[[tdh,ih],s],
  beast: [[b,ii],s,t],
  coaxed: [[k,ohw],k,s,t],
  into: [[ih,n],[t,oo]],
  lonely:[[l,ohw],n,[l,eh]],
  purpose:[[p,er],[p,ih],s],
}
export const page34: Record<string, GlyphOrJoin[]> = {
  up: [[uh, p]],
  no: [[n, ah]],
  sou: [[s, ow]],
  we: [[v, eh]],
  eas: [[ii, s]]
}
export const page35: Record<string, GlyphOrJoin[]> = {
  odd:[[oh,d]],
  door:[[d,or]],
  rotate:[[r,ohw],[t,ey],t],
  it:[[ih,t]],
  around:[uh,[r,ow],n,d],
  forbidden:[[f,or],[b,ih],[d,ih],n],
  axis: [[ah,k],[s,ih],s],
  and: [[ah,n],d],
  partially: [[p,ar],[sh,uu],[l,ii]],
  summon: [[s,uh],[m,ih],n],
  a: [uh],
  disquiet:[[d,ih],s,k,[v,aj],[eh,t]],
  being: [[b,ii],[ih,ng]]
}
export const page41: Record<string, GlyphOrJoin[]> = {
  the:[[tdh,uh]],
  far:[[f,ar]],
  shore:[[sh,or]],
  shadow:[[sh,ah],[d,ohw]],
  oubliette:[[oo,b],[l,ii],[eh,t]],
  stolen:[s,[t,ohw],[l,ih],n],
  device:[[d,ii],[vh,aj],s],
  sword:[[s,or],d],
  of:[[uh,vh]],
  thee:[[tdh,ii]],
  heir:[air],
  ruin: [[r, oo], [ih, n]],
  seekers: [[s, ii], [k, er],z],
  arrival:[uh,[r,aj],[vh,uu],l],
  a: [uh],
  key:[[k,ii]],
  is:[[ih,z]],
  no:[[n,ohw]],
  mere: [[m,ear]],
  toy: [[t,oy]]
}
export const page43: Record<string, GlyphOrJoin[]> = {
  ruin: [[r,oo],[ih,n]],
  seeker: [[s,ii],[k,er]],
  begins: [[b,eh],[g,ih],n,z],
  to: [[t,oo]],
  understand: [[uh,n],[d,er],s,[t,ah],n,d],
}

export const page44: Record<string, GlyphOrJoin[]> = {
  much: [[m,uh],tj],
  is: [[ih,z]],
  hidden: [[h,ih],[d,ih],n],
  in: [[ih,n]],
  this:[[tdh,ih],s],
  world: [[v,er],l,d],
  bound: [[b,ow],n,d],
  behind: [[b,ii],[h,aj],n,d],
  the: [[tdh,uh]],
  power: [[p,ow],er],
  of: [[uh,vh]],
  proove:[p,[r,oo],vh],
  to: [[t,oo]],
  those: [[tdh,ohw],z],
  who: [[h,oo]],
  gave: [[g,ey],vh],
  their: [[tdh,air]],
  core:[[k,or]],
  that: [[tdh,ah],t],
  you:[[j,oo]],
  know: [[n,ohw]],
  it:[[ih,t]],
  deeply:[[d,ii],p,[l,ii]],


  open:[[ohw,p],[eh,n]],
  vaults:[[vh,oh],l,t,s],
  left:[[l,eh],f,t],
  help:[[h,eh],l,p],
  wise:[[v,aj],z],
  ruin:[[r,oo],[ih,n]],
  seekers:[[s,ii],[k,er],z],

  souls: [[s,ohw],l,z],
  stayed:[s,[t,ey],d],
  guide:[[g,aj],d],
  and: [[ah,n],d],
  receive: [[r,ii],[s,ii],vh],
  gift:[[g,ih],f,t],

  follow:[[f,oh],[l,ohw]],
  monolith:[[m,oh],[n,ohw],[l,ih],tfh],
}
export const page45: Record<string, GlyphOrJoin[]> = {
  extinguish: [[eh,k],s,[t,ih],ng,g,[vh,ih],sh],
  the: [[tdh,uh]],
  beings:[[b,ii],[k,ih],n,z],
  last: [[l,ah],s,t],
  spark: [s,[p,ar],k],
  and: [[ah,n],d],
  become: [[b,ii],[k,uh],m],
  a: [uh],
  fresh:[f,[r,eh],sh],
  martyr:[[m,ar],[t,er]],
  courage: [[k,er],[ih,dj]],
  that: [[tdh,ah],t],
  is:[[ih,z]],
  untempered:[[uh,n],[t,eh],m,[p,er],d],
  by: [[b,aj]],
  kindness: [[k,aj],n,d,[n,ih],z],
  risks: [[r,ih],s,k,s],
  eating:[[ii,t],[ih,ng]],
  itself: [[ih,t],[s,eh],l,f],
  forever: [[f,or],[eh,vh],er],
}
export const page46: Record<string, GlyphOrJoin[]> = {
  wisdom:[[v,ih],z,[d,uh],m],
  that: [[tdh,ah],t],
  is: [[ih,z]],
  untempered:[[uh,n],[t,eh],m,[p,er],d],
  by: [[b,aj]],
  kindness: [[k,aj],n,d,[n,ih],s],
  no: [[n,ohw]],
  at:[[ah,t]],
  all:[[oh,l]],
  be: [[b,ii]],
  free: [f,[r,ii]],
}
export const page49: Record<string, GlyphOrJoin[]> = {
  the:[[tdh,uh]],
  golden: [[g, ohw], l, [d, ih], n],
  path: [[p,ah],tfh],
  greatest:[g,[r,ey],[t,ih],s,t],
  spell:[s,[p,eh],l],
}
// page 50 has no text
export const page51: Record<string, GlyphOrJoin[]> ={
  cards:[[k,ar],d,z],
  did: [[d,ih],d],
  you: [[j,oo]],
  retain: [[r,ii],[t,ey],n],
  letter: [[l,eh],[t,er]],
  from:[f,[r,uh],m],
  us:[[uh,s]],
  immerse:[[ih,m],[er,s]],
  it: [[ih,t]],
  in: [[ih,n]],
  water:[[v,oh],[t,er]],
  for:[[f,or]],
  to:[[t,oo]],
  see:[[s,ii]],
  a: [uh],
  secret: [[s,ii],k,[r,ih],t],
  message:[[m,eh],[s,ih],dj],
  parry: [[p,air],ii],
  time:[[t,aj],m],
}
export const page52: Record<string, GlyphOrJoin[]> = {
  maze: [[m, ey], z],
  le: [[l, eh]],
  ri: [[r, aj]],
  up: [[uh, p]],
  doh: [[d, ow]],
  no: [[n, ah]],
  sou: [[s, ow]],
  we: [[v, eh]],
  eas: [[ii, s]]
}
// page 53 has no text
export const page54: Record<string, GlyphOrJoin[]> = {
  fox: [[f, oh], k, s],
  sword: [[s, or], d],
  find: [[f, aj], n, d],
  some: [[s, uh], m],
  rare: [[r, air]],
  golden: [[g, ohw], l, [d, uh], n],
  statues: [s, [t, ah], [tj, oo], z],
  traverse:[t,[r,uh],[vh,er],s],
  the: [[tdh,uh]],
  glow: [g,[l,ohw]],
  to: [[t,oo]],
  visit:[[vh,ih],[z,ih],t],
  strange:[s,t,[r,ey],n,dj],
  beings: [[b,ii],[ih,ng],z],
  un_: [[uh,n]],
  sing:[[s,ih],ng],
  them: [[tdh,eh],m],
  greatest: [g,[r,ey],[t,ih],s,t],
  song:[[s,oh],ng],
  of:[[uh,vh]],
  path:[[p,ah],tfh],
  as:[[ah,z]],
  seen:[[s,ii],n],
  from:[f,[r,uh],m],
  within:[[v,ih],[tfh,ih],n],
}
export const page55: Record<string, GlyphOrJoin[]> = {
  near: [[n,ear]],
  an: [[ah,n]],
  ancient: [[ey,n],[tj,ih],n,t],
  tomb: [[t,oo],m],

  plundered: [p,[l,uh],n,[d,er],d],
  for: [[f,or]],
  its: [[ih,t],s],
  blade: [b,[l,ey],d],

  lies:[[l,aj],z],
  a: [uh],
  special: [s,[p,eh],[sh,uu],l],
  place: [p,[l,ey],s],

  under: [[uh,n],[d,er]],
  the: [[tdh,uh]],
  moon: [[m,oo],n],

  contemplate: [[k,oh],n,[t,eh],m,p,[l,ey],t],
  this:[[tdh,ih],s],
  prayer:[p,[r,ey],er],
}
export const xtra: Record<string, GlyphOrJoin[]> = {
  light:[[l,aj],t],
  candle:[[k,ah],n,[d,uu],l],
  weird: [[v,ear],d],
  critters: [k,[r,ih],[t,er],z],
}
// export const words: Record<string, GlyphOrJoin[]> = {
//      take:[[t,ey],k],
//      hi: [[h,aj]],
//      are: [ar],
//      you: [[j,oh]],
//      new: [[n,oh]],
//      lies: [[l,aj],z],

//     //  the:
//     //  altar
//     //  has no soul

//      where:[[v,air]],
//      do:[[d,oo]],
//      hide:[[h,aj],d],
//      but:[[b,uh],t],
//      go: [[g,ohw]],
//      no: [[n,ohw]],
//      be:[[b,ii]],
//      at: [[ah,t]],
//      all:[[oh,l]],
//      that:[[tdh,ah],t],


//      // for here hear are enough left that
//      // found toy great  have width you
//      // nothing water wide brave use adjust sign
//      // yet  they was wisdom tool toy checkpoint
//      //  guard rare  so know not north war kindness certain
//      // by item right mere  south


//     rune: [[r, oo], n],
//     runic: [[r,oo],n,[ih,k]],
// }
